# --- settings

id: "mac-m1-pro"
host: localhost
port: 8080
log: llamazoo.log
deadline: 180
sessions: "/home/sessions"

# --- pods

  -
    threads: 6
    gpus: [ 0, 0 ]
    model: wizard

  -
    threads: 1
    gpus: [ 50, 50 ]
    model: airoboros

# --- models

models:

  - 
    id: airoboros
    name: Airoboros 7B
    path: ~/models/7B/airoboros-7b-ggml-q4_0.bin
    locale: en_US

    preamble:
    prefix: "USER:"
    suffix: "ASSISTANT:"

    contextsize: 2048
    predict: 1024

    janus: 1
    depth: 200
    scale: 0.97
    hi: 0.99
    lo: 0.96

    temp: 0.1
    topk: 8
    topp: 0.4
    typicalp: 1.0
    penaltyrepeat: 1.1
    penaltylastn: -1
    mirostat: 2
    mirostatent: 0.1
    mirostatlr: 0.1     

  -
    id: wizard
    name: WizardLM 7B
    path: ~/models/7B/wizardLM-7B.ggmlv3.q4_0.bin
    locale: en_US

    preamble:
    prefix: "### Instruction:"
    suffix: "### Response:"

    contextsize: 2048
    predict: 1024

    janus: 1
    depth: 200
    scale: 0.97
    hi: 0.99
    lo: 0.96

    temp: 0.1
    topk: 8
    topp: 0.4
    typicalp: 1.0
    penaltyrepeat: 1.1
    penaltylastn: -1
    mirostat: 0
    mirostatent: 0
    mirostatlr: 0
