# --- settings

id: "mac-m1-pro"
host: localhost
port: 8080
log: llamazoo.log
deadline: 180
numa: 0
lowvram: 0
sessions: "/home/sessions"
maxsessions: 100

# --- pods

  -
    threads: 6
    gpus: [ 0, 0 ]
    model: wizard
    mode:

  -
    threads: 1
    gpus: [ 50, 50 ]
    model: airoboros
    mode:

# --- models

models:

  - 
    id: airoboros
    name: Airoboros 7B
    path: ~/models/7B/airoboros-7b-ggml-q4_0.bin
    gqa: 1
    preamble:
    prefix: "USER:"
    suffix: "ASSISTANT:"
    contextsize: 2048
    predict: 1024
    temp: 0.1
    topk: 8
    topp: 0.4
    repeatpenalty: 1.1
    repeatlastn: -1
    mirostat: 2
    mirostattau: 0.1
    mirostateta: 0.1      

  -
    id: wizard
    name: WizardLM 7B
    path: ~/models/7B/wizardLM-7B.ggmlv3.q4_0.bin
    gqa: 1
    preamble:
    prefix: "### Instruction:"
    suffix: "### Response:"
    contextsize: 2048
    predict: 1024
    temp: 0.1
    topk: 8
    topp: 0.4
    repeatpenalty: 1.1
    repeatlastn: -1
    mirostat: 0
    mirostattau: 0
    mirostateta: 0
