# --- settings

id: "mac-m1-pro"
host: localhost
port: 8080
log: collider.log
deadline: 180
swap: "/home/sessions"
debug:

# --- pods

  -
    model: default
    threads: 6
    gpus: [ 0 ]
    batchsize: 512

# --- models

models:

  - 
    id: default
    name: Airoboros 7B
    path: ~/models/7B/airoboros-7b-ggml-q4_0.bin

    prompt: custom
    locale: en_US
    system: "### System:\n\nToday is {DATE}. {SYSTEM}"
    user: "\n\n### User:\n\n{USER}"
    assistant: "\n\n### Assistant:\n\n{ASSISTANT}"    

    preamble:
    prefix: "USER:"
    suffix: "ASSISTANT:"

    contextsize: 2048
    predict: 1024

    janus: 1
    depth: 200
    scale: 0.97
    hi: 0.99
    lo: 0.96

    temperature: 0.1
    top_k: 8
    top_p: 0.4
    typicalp: 1.0
    repetition_penalty: 1.1
    penaltylastn: -1

    mirostat: 2
    mirostatent: 0.1
    mirostatlr: 0.1     
