# --- server settings

id: "mac-m1-pro"
host: localhost
port: 8080
pods: 3
threads: [ 2, 8, 4 ]
gpus: [ 0, 0, 0 ]
gpulayers: [ 100, 0, 0 ]
log: llamazoo.log
deadline: 180
numa: 0
lowvram: 0
sessions: "/home/sessions"
maxsessions: 100

# --- working modes

modes:
  default: airoboros-13b
  fast: wizardlm-7b

# --- available models

models:

  - 
    id: airoboros-7b
    name: Airoboros 7B
    path: ~/models/7B/airoboros-7b-ggml-q4_0.bin
    preamble:
    prefix: "USER:"
    suffix: "ASSISTANT:"
    contextsize: 2048
    predict: 1024
    temp: 0.1
    topk: 10
    topp: 0.5
    repeatpenalty: 1.1
    repeatlastn: -1
    mirostat: 2
    mirostattau: 0.1
    mirostateta: 0.1      

  -
    id: wizard-7b
    name: WizardLM 7B
    path: ~/models/7B/wizardLM-7B.ggmlv3.q4_0.bin
    preamble:
    prefix: "### Instruction:"
    suffix: "### Response:"
    contextsize: 2048
    predict: 1024
    temp: 0.1
    topk: 10
    topp: 0.5
    repeatpenalty: 1.1
    repeatlastn: -1
    mirostat: 0
    mirostattau: 0
    mirostateta: 0
